apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: fastapi-app-binding
  namespace: demo
spec:
  params:
  - name: GIT_REPO
    value: $(body.repository.url)
  - name: GIT_REVISION
    value: $(body.head_commit.id)
