apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: fastapi-app-tt
  namespace: demo
spec:
  params:
  - name: IMAGE_NAME
    description: Name of the container image
    default: fastapi-quickstart-img
  - name: IMAGE_TAG
    description: The tag of the container image
    default: '2.0'
  - name: GIT_REPO
    description: The name of the deployment git repo
    default: 'https://github.com/rwalker-redhat/fastapi-quickstart-project.git'
  - name: GIT_REVISION
    description: The name of the deployment git repo
    default: main
  - name: MESSAGE
    description: The name of the deployment git repo
    default: 'message from event trigger'

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-$(tt.params.IMAGE_TAG)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: fetch-build
      params:
      - name: IMAGE_NAME
        value: >-
          image-registry.openshift-image-registry.svc:5000/demo/fastapi-quickstart-img
      - name: IMAGE_TAG
        value: 2.0
      - name: GIT_REPO
        value: $(tt.params.GIT_REPO)
      - name: GIT_REVISION
        value: $(tt.params.GIT_REVISION)
      - name: MESSAGE
        value: 'triggered'
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: shared-workspace
      - name: ssh-creds
        secret:
          secretName: pipeline-ssh-key