apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: fastapi-trigger
  namespace: demo
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: fastapi-app-binding
  template:
    ref: fastapi-app-tt