apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pipeline-workspace
  namespace: pipeline-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
