imagePullSecrets:
  - name: ocpregcred

imageCredentials:
  registry: image-registry.openshift-image-registry.svc:5000
  username: developer
  password: sha256~XcdJ5EPXTVcQEuowrwDmEYfK_rSFvGWZE0Kwu28gvKY

appName: fastapi-quickstart

imageName: fastapi-quickstart-app
tag: '1.3'

ports:
  port: 8000
  targetPort: 8000

namespace: ocp-fastapi-quickstart-project
